# Generated by Django 5.2 on 2025-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('third_party', 'Third-Party Dev')], default='client', max_length=50),
        ),
    ]
