# Generated by Django 5.2 on 2025-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='display_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
