# Generated by Django 5.2 on 2025-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rechargerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='billing_method',
            field=models.CharField(choices=[('CPM', '按展示计费'), ('CPC', '按点击计费'), ('CPT', '按时长计费')], default='CPM', max_length=10),
        ),
        migrations.AddField(
            model_name='ad',
            name='cpc_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ad',
            name='cpm_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ad',
            name='cpt_price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ad',
            name='cpt_unit_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adinteraction',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adinteraction',
            name='action',
            field=models.CharField(choices=[('display', 'Display'), ('click', 'Click'), ('watch', 'Watch')], max_length=10),
        ),
    ]
